### ISSUE TITLE
Add support for non-UTF8 attributes

### ISSUE THREAD

**Issue by nitnelave** [kanidm/ldap3_proto#7]
Currently, `LdapPartialAttributes` require the values to be `String`, i.e. a valid UTF-8 attribute.

However, a fairly common LDAP attribute is `JpegPhoto` where the raw bytes of the JpegPhoto are sent. It's not representable as a `String`. It should instead be a `OsString` or `Vec<u8>`.

WDYT? If you want this (it would be a breaking change, I understand) I can try to work on a PR, but otherwise I'll just have my own fork.

**Comment by Firstyear** [comment]
I think you're right, we should represent this as a Vec<u8>. I'd be happy to review and help with the PR :)

**Comment by Firstyear** [comment]
@nitnelave Sorry for the huge delay on this. I'm going to make this change within the week and will update to 0.3 to resolve.
